--- Makefile.orig	2017-08-05 14:52:57.119213990 -0700
+++ Makefile	2017-08-05 15:02:08.977255584 -0700
@@ -1,10 +1,11 @@
 VERSION = $(shell git describe --tags)
-PREFIX = /usr/local
+PREFIX = /usr
 GTK = gtk+-3.0
 VTE = vte-2.91
 TERMINFO = ${PREFIX}/share/terminfo
 
-CXXFLAGS := -std=c++11 -O3 \
+CXXFLAGS := ${CXXFLAGS} \
+            -std=c++11 -O3 \
 	    -Wall -Wextra -pedantic \
 	    -Winit-self \
 	    -Wshadow \
@@ -18,8 +19,7 @@
 	    -DNDEBUG \
 	    -D_POSIX_C_SOURCE=200809L \
 	    -DTERMITE_VERSION=\"${VERSION}\" \
-	    ${shell pkg-config --cflags ${GTK} ${VTE}} \
-	    ${CXXFLAGS}
+	    ${shell pkg-config --cflags ${GTK} ${VTE}}
 
 ifeq (${CXX}, g++)
 	CXXFLAGS += -Wno-missing-field-initializers
@@ -29,7 +29,7 @@
 	CXXFLAGS += -Wimplicit-fallthrough
 endif
 
-LDFLAGS := -s -Wl,--as-needed ${LDFLAGS}
+LDFLAGS := -s ${LDFLAGS}
 LDLIBS := ${shell pkg-config --libs ${GTK} ${VTE}}
 
 termite: termite.cc url_regex.hh util/clamp.hh util/maybe.hh util/memory.hh
@@ -40,8 +40,8 @@
 	install -Dm755 termite ${DESTDIR}${PREFIX}/bin/termite
 	install -Dm644 config ${DESTDIR}/etc/xdg/termite/config
 	install -Dm644 termite.desktop ${DESTDIR}${PREFIX}/share/applications/termite.desktop
-	install -Dm644 man/termite.1 ${DESTDIR}${PREFIX}/share/man/man1/termite.1
-	install -Dm644 man/termite.config.5 ${DESTDIR}${PREFIX}/share/man/man5/termite.config.5
+	install -Dm644 man/termite.1 ${DESTDIR}${PREFIX}/man/man1/termite.1
+	install -Dm644 man/termite.config.5 ${DESTDIR}${PREFIX}/man/man5/termite.config.5
 	tic -x -o ${DESTDIR}${TERMINFO} termite.terminfo
 
 uninstall:
