#!/usr/bin/env bash

# Builds *any* LxQt component. Put the tarball in the same directory as the SlackBuild and run it.

TMP=${TMP:-/tmp}
BUILD=1
TAG=dc

SRC=$(echo ./*.tar.xz)
PRGNAM=$(basename "$SRC" | cut -d - -f 1)
VERSION=$(basename "$SRC" .tar.xz | cut -d - -f 2)

PKG="$TMP/package-$PRGNAM"


if [[ -z "$ARCH" ]]; then
  case $( uname -m ) in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
    *) ARCH=$( uname -m ) ;;
  esac
fi

